### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by alexwennerberg** [Gekkio/mooneye-gb#40] opened 2018-06-11 19:16 UTC
I tried to build this emulator, but I get the following build error (on MacOS):

```error[E0658]: non-reference pattern used to match a reference (see issue #42640)
  --> src/frontend/renderer.rs:57:7
   |
57 |       FrameState::Even => FrameState::Odd,
   |       ^^^^^^^^^^^^^^^^ help: consider using a reference: `&FrameState::Even`

error[E0658]: non-reference pattern used to match a reference (see issue #42640)
  --> src/frontend/renderer.rs:58:7
   |
58 |       FrameState::Odd => FrameState::Even,
   |       ^^^^^^^^^^^^^^^ help: consider using a reference: `&FrameState::Odd
error: aborting due to 2 previous errors

error: Could not compile `mooneye-gb`.
```

Any ideas what is causing this and how to fix? Thanks! Very interested in and excited about this project.

**Comment by alexwennerberg** [comment] 2018-06-11 20:47
Not an expert on this repo (just playing around / experimenting with it) but it looks like this is from commit 2a054027ebb977dd502a6fcd7b312ce3e79b2834

I built 94a8685627d774fb7f565cd5f0e555e48a1a4b59 and it worked & could run a ROM.

Also, looks like I have to install the sdl2 library on Mac. (figured this out from reading the travis file). I can submit a PR to add this to the documentation if you'd like. The documentation for running the GUI seems out of date as well: "Follow the instructions" -- I don't see any instructions.

Awesome project!

**Comment by Gekkio** [comment] 2018-06-11 21:54
Sorry! That compilation error was caused by an accidental bump of minimum Rust version to 1.26. It wasn't intended but I don't provide backwards compatibility, so I'll just leave it as it is. I added a mention of the minimum Rust version and SDL2 to the readme.

The GUI problem was caused by a backwards-incompatible change in imgui, which wasn't caught because it still compiled without errors. I've added a workaround in a3fb4a23bdd83db2e9244640fa8c82decd0fe92a so you should see the notification now if you're missing the boot ROM.

**Comment by alexwennerberg** [comment] 2018-06-12 00:08
Thanks! Now it seems, however, that when I try and load a game ROM (which worked before), I get this error:

```
thread 'main' panicked at 'index out of bounds: the len is 256 but the index is 331', /Users/travis/build/rust-lang/rust/src/libcore/slice/mod.rs:865:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic_bounds_check
   9: mooneye_gb::config::cartridge::Cartridge::from_data
  10: mooneye_gb::config::cartridge::Cartridge::from_path
  11: mooneye_gb::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
```

**Comment by Gekkio** [comment] 2018-08-14 18:47
The problems have been fixed so I'll close this

**Closed by Gekkio** 2018-08-14 18:47 UTC
